# Generated by Django 3.1.4 on 2021-03-11 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Public', models.BooleanField()),
                ('Like', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Singer', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Like', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Music', models.FileField(upload_to='music/')),
                ('CategoryID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='Rate_music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Music_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.music')),
                ('UserID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate_album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.album')),
                ('UserID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group_music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.album')),
                ('Music_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.music')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.album')),
                ('UserID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
