# Generated by Django 3.1.4 on 2021-03-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate_album',
            name='Like',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate_music',
            name='Like',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
