# Generated by Django 3.1.4 on 2021-03-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210313_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate_music',
            name='isLike',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
