# Generated by Django 3.1.4 on 2021-03-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rate_music_islike'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate_album',
            name='isLike',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
