# Generated by Django 3.1.4 on 2021-03-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rate_album_islike'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Quality',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
