# Generated by Django 3.1.4 on 2021-03-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_cart_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Quality',
        ),
    ]
