# Generated by Django 3.1.4 on 2021-03-17 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_remove_cart_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalPrice', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.album')),
                ('BillID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.bill')),
            ],
        ),
    ]
