# Generated by Django 3.1.4 on 2021-03-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_bill_billproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Delivery_Address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='Name_of_consignee',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='Phone_Number',
            field=models.IntegerField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
