# Generated by Django 3.1.4 on 2021-03-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210319_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='Delivery_Address',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='Name_of_consignee',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='TotalPrice',
        ),
        migrations.AddField(
            model_name='bill',
            name='Bill',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='BillProduct',
        ),
    ]
