# Generated by Django 3.1.4 on 2021-03-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210322_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Shipped',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
