# Generated by Django 3.1.4 on 2021-04-07 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0011_bill_shipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfotmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DateofBirth', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Phone', models.IntegerField()),
                ('UserID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
